#!/bin/bash

set -e
cd "$(dirname "$0")"

do_convert () {
    local FOLDER="$1"
    local SCALE="$2"
    local ANAME="$3"
    local DEVICE="$4"
    local QUALITY="$5"

    find "$FOLDER" -name 'render_*.png' -print \
        | xargs -n 1 basename \
        | xargs -n 1 -I '{}' convert "${FOLDER}/{}" -scale "$SCALE" -ordered-dither o3x3,4 -depth 2 "${FOLDER}/${SCALE}_{}"

    if [ "$ANAME" != "" ] ; then
        local COMPRESSION="3" # 1 .. 7
        convert -delay 6 -loop 0 "${FOLDER}/${SCALE}_render_*.png" "${FOLDER}/${ANAME}_${SCALE}.gif"

        [ -e "${FOLDER}/${ANAME}_${SCALE}_8_RGB222.mm" ] && rm "${FOLDER}/${ANAME}_${SCALE}_8_RGB222.mm"
        monkeym -c 2 -d "$DEVICE" -f 10 -o "$FOLDER" -p "$COMPRESSION" -q "$QUALITY" -s 3 -v "${FOLDER}/${ANAME}_${SCALE}.gif" -w
        mv "${FOLDER}/${ANAME}_${SCALE}_${SCALE}_8_RGB222.mm" "${FOLDER}/${ANAME}_${SCALE}_8_RGB222.mm"
        sed -i "s/${ANAME}_${SCALE}_${SCALE}_8_RGB222/${ANAME}_${SCALE}_8_RGB222/" "${FOLDER}/${ANAME}_${SCALE}.mmm"
    fi
}

do_mmm () {
    FOLDER="$1"
    ANAME="$2"
    SCALE_1="$3"
    SCALE_2="$4"

    if [ ! -e "${FOLDER}/${ANAME}_${SCALE_1}.mmm" ] || [ ! -e "${FOLDER}/${ANAME}_${SCALE_2}.mmm" ] ; then
        echo "${FOLDER}/${ANAME}_${SCALE_1}.mmm or ${FOLDER}/${ANAME}_${SCALE_2}.mmm not found"
        return 1
    fi

    MMM_1="$(grep -v '#' "${FOLDER}/${ANAME}_${SCALE_1}.mmm" | grep -vE '^$')"
    MMM_2="$(grep -v '#' "${FOLDER}/${ANAME}_${SCALE_2}.mmm" | grep -vE '^$')"

    echo "# This is a generated file. It is highly recommended that you DO NOT edit this file.
# Monkey Motion Manifest file
# Video file: $(pwd)/${FOLDER}/${ANAME}.gif
# Output File Path: $(pwd)/${FOLDER}
# Image Quality: 3
# ${SCALE_1} part number mappings
${MMM_1}
# ${SCALE_2} part number mappings
${MMM_2}" > "${FOLDER}/${ANAME}.mmm"

    rm "${FOLDER}/${ANAME}_${SCALE_1}.mmm"
    rm "${FOLDER}/${ANAME}_${SCALE_2}.mmm"
}

do_convert smoke 218x218 smoke vivoactive4s 2
do_convert smoke 260x260 smoke vivoactive4 2
do_mmm smoke smoke 218x218 260x260
