#!/bin/bash

set -e
cd "$(dirname "$0")"

do_convert () {
    TYPE="$1"
    SCALE="$2"
    DEVICE="$3"
    QUALITY="$4"

    find "$TYPE" -name 'Blender*.png' -print \
        | xargs -n 1 basename \
        | xargs -n 1 -I '{}' convert "${TYPE}/{}" -scale "$SCALE" -ordered-dither o3x3,4 -depth 2 "${TYPE}/${SCALE}_{}"

    convert -delay 6 -loop 0 "${TYPE}/${SCALE}_Blender*.png" "${TYPE}/${TYPE}_${SCALE}.gif"

    [ -e "${TYPE}/${TYPE}_${SCALE}_8_RGB222.mm" ] && rm "${TYPE}/${TYPE}_${SCALE}_8_RGB222.mm"
    monkeym -c 2 -d "$DEVICE" -f 10 -o "$TYPE" -p 3 -q "$QUALITY" -s 3 -v "${TYPE}/${TYPE}_${SCALE}.gif" -w
    mv "${TYPE}/${TYPE}_${SCALE}_${SCALE}_8_RGB222.mm" "${TYPE}/${TYPE}_${SCALE}_8_RGB222.mm"
    sed -i "s/${TYPE}_${SCALE}_${SCALE}_8_RGB222/${TYPE}_${SCALE}_8_RGB222/" "${TYPE}/${TYPE}_${SCALE}.mmm"
}

do_mmm () {
    TYPE="$1"

    if [ ! -e "${TYPE}/${TYPE}_218x218.mmm" ] || [ ! -e "${TYPE}/${TYPE}_260x260.mmm" ] ; then
        echo "${TYPE}/${TYPE}_218x218.mmm or ${TYPE}/${TYPE}_260x260.mmm not found"
        return 1
    fi

    MMM_218x218="$(grep -v '#' "${TYPE}/${TYPE}_218x218.mmm" | grep -vE '^$')"
    MMM_260x260="$(grep -v '#' "${TYPE}/${TYPE}_260x260.mmm" | grep -vE '^$')"

    echo "# This is a generated file. It is highly recommended that you DO NOT edit this file.

# Monkey Motion Manifest file
# Video file: $(pwd)/${TYPE}/${TYPE}.gif
# Output File Path: $(pwd)/${TYPE}
# Image Quality: 3

# 218x218 part number mappings
${MMM_218x218}
# 260x260 part number mappings
${MMM_260x260}" > "${TYPE}/${TYPE}.mmm"

    rm "${TYPE}/${TYPE}_218x218.mmm"
    rm "${TYPE}/${TYPE}_260x260.mmm"
}

do_convert enter 218x218 vivoactive4s 3
do_convert enter 260x260 vivoactive4 3
do_mmm enter

do_convert leave 218x218 vivoactive4s 2
do_convert leave 260x260 vivoactive4 2
do_mmm leave
